# The content of this file was generated by IBM Cloud
# Do not modify it as it might get overridden

from ibm_cloud_env import IBMCloudEnv
from . import service_manager
# GENERATE IMPORT HERE

def initServices(app):
    IBMCloudEnv.init()
    # GENERATE HERE