# The content of this file was generated by IBM Cloud
# Do not modify it as it might get overridden

from ibmcloudenv import IBMCloudEnv
from . import service_manager
IBMCloudEnv.init()

# GENERATE IMPORT HERE

def initServices(app):
	# GENERATE HERE
	return
